name: Java CI with Maven - Staged Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test1:
    name: Run Test1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Only AppTest1
        run: mvn test

      - name: Generate Surefire HTML Report
        run: mvn surefire-report:report

      - name: Upload Surefire Report for Test1
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report-test1
          path: target/site/

  test2:
    name: Run Test2
    runs-on: ubuntu-latest
    needs: test1

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Only AppTest2
        run: mvn test

      - name: Generate Surefire HTML Report
        run: mvn surefire-report:report

      - name: Upload Surefire Report for Test2
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report-test2
          path: target/site/

  test3:
    name: Run Test3
    runs-on: ubuntu-latest
    needs: test2

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Only AppTest3
        run: mvn test

      - name: Generate Surefire HTML Report
        run: mvn surefire-report:report

      - name: Upload Surefire Report for Test3
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report-test3
          path: target/site/
